### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by boaty82** [ge0ffrey/packing-santas-sleigh#1]
Many of the dependencies your classes have of the optaplanner lib do not exist

example 
org.optaplannerdelirium.pss.persistence.PssExporter
relies upon org.optaplanner.core.impl.solution.Solution
but this isn't in the 6.1.0-final jar?

**Comment by ge0ffrey** [comment]
This was written versus a snapshot version. I suspect you 'll get it working if you figure out from which line to apply this upgrade recipe:
  http://www.optaplanner.org/download/upgradeRecipe/upgradeRecipe6.1.html

That being said, this project isn't supported nor active - so there's no intention to keep it compilable (OTH I don't want to throw away the code either).

**Comment by boaty82** [comment]
Fair do's - just thought I'd ask and be optimistic ;o)
